Update arm64ec_wine.yml

diff --git a/.github/workflows/arm64ec_wine.yml b/.github/workflows/arm64ec_wine.yml
--- a/.github/workflows/arm64ec_wine.yml
+++ b/.github/workflows/arm64ec_wine.yml
@@ -247,6 +247,32 @@ jobs:
             fi
           fi
 
+          FILE3="dlls/wdscore/wdscore.spec"
+          if [ -f "$FILE3" ]; then
+            if grep -q '@ stub' "$FILE3"; then
+              echo "Cleaning wdscore.spec stubs..."
+              sed -i '/CDynamicArray/d' "$FILE3"
+              echo "✔ wdscore stubs cleaned"
+            else
+              echo "✔ wdscore already cleaned or not found"
+            fi
+          fi
+
+          # 2. ntdll virtual.c 미초기화 변수 방어 (컴파일러 경고 해결)
+          FILE="dlls/ntdll/unix/virtual.c"
+          if [ -f "$FILE" ]; then
+            if grep -q 'unsigned int vprot, sec_flags;' "$FILE"; then
+              echo "Fixing uninitialized vprot in virtual.c..."
+              sed -i 's/unsigned int vprot, sec_flags;/unsigned int vprot = 0, sec_flags = 0;/g' "$FILE"
+            fi
+          fi
+
+          FILE="dlls/ntdll/unix/loader.c"
+          if ! grep -q '/aarch64-windows' "$FILE"; then
+            echo "Patching PE directory mapping..."
+            sed -i 's|/x86_64-windows|/aarch64-windows|g' "$FILE"
+          fi
+
           FILE="dlls/ntdll/loader.c"
           if grep -q 'xtajit64\.dll' "$FILE"; then
             echo "Replacing xtajit64.dll with libarm64ecfex.dll..."
@@ -275,7 +301,8 @@ jobs:
               }' "$FILE"
           fi
 
-          PATCH_LIST="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/1.patch"
+          PATCH_LIST="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/1.patch
+                      https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/2.patch"
 
           echo "Applying external patches..."
           for URL in $PATCH_LIST; do
