Update arm64ec_wine.yml

diff --git a/.github/workflows/arm64ec_wine.yml b/.github/workflows/arm64ec_wine.yml
--- a/.github/workflows/arm64ec_wine.yml
+++ b/.github/workflows/arm64ec_wine.yml
@@ -268,6 +268,26 @@ jobs:
           find . -name "loader.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} + 2>/dev/null || true
           find . -name "server.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} + 2>/dev/null || true
           echo "路径修复完成"
+          
+          PATCH_URL="https://raw.githubusercontent.com/lacamar/wine-arm64ec-rpm/refs/heads/main/wine/2026.03.15_bylaws.patch"
+          PATCH_FILE="syscall.patch"
+          echo "Applying external patch..."
+          wget -q -O "$PATCH_FILE" "$PATCH_URL"
+          if git apply --check "$PATCH_FILE"; then
+              echo "✔ Patch can be applied cleanly"
+              git apply --whitespace=fix "$PATCH_FILE"
+          elif git apply --3way --check "$PATCH_FILE"; then
+              echo "⚠ Applying patch with 3-way merge"
+              git apply --3way --whitespace=fix "$PATCH_FILE"
+          else
+              echo "❌ Patch failed, generating rejects"
+              git apply --reject --whitespace=fix "$PATCH_FILE" || true
+              echo "❌ Patch could not be fully applied"
+              find . -name "*.rej"
+              exit 1
+          fi
+          echo "✔ Patch applied successfully"
+          
           FILE="dlls/atiadlxx/atiadlxx_main.c"
           if grep -q 'InterlockedOr(&dummy, 0)' "$FILE"; then
             sed -i 's|InterlockedOr(&dummy, 0)|InterlockedOr((volatile long *)&dummy, 0)|g' "$FILE"
@@ -334,25 +354,6 @@ jobs:
           else
             echo "✔ wdscore already cleaned or not found"
           fi
-
-          PATCH_URL="https://raw.githubusercontent.com/lacamar/wine-arm64ec-rpm/refs/heads/main/wine/2026.03.15_bylaws.patch"
-          PATCH_FILE="syscall.patch"
-          echo "Applying external patch..."
-          wget -q -O "$PATCH_FILE" "$PATCH_URL"
-          if git apply --check "$PATCH_FILE"; then
-              echo "✔ Patch can be applied cleanly"
-              git apply --whitespace=fix "$PATCH_FILE"
-          elif git apply --3way --check "$PATCH_FILE"; then
-              echo "⚠ Applying patch with 3-way merge"
-              git apply --3way --whitespace=fix "$PATCH_FILE"
-          else
-              echo "❌ Patch failed, generating rejects"
-              git apply --reject --whitespace=fix "$PATCH_FILE" || true
-              echo "❌ Patch could not be fully applied"
-              find . -name "*.rej"
-              exit 1
-          fi
-          echo "✔ Patch applied successfully"
 
       # ------------------------------------------------------------
       # 8. 生成 configure 脚本
