Update arm64ec_wine.yml

diff --git a/.github/workflows/arm64ec_wine.yml b/.github/workflows/arm64ec_wine.yml
--- a/.github/workflows/arm64ec_wine.yml
+++ b/.github/workflows/arm64ec_wine.yml
@@ -263,25 +263,6 @@ jobs:
             echo "✔ InterlockedOr already patched or not found"
           fi         
 
-          PATCH_URL="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/2.patch"
-          PATCH_FILE="syscall.patch"
-          echo "Applying external patch..."
-          wget -q -O "$PATCH_FILE" "$PATCH_URL"
-          if git apply --check "$PATCH_FILE"; then
-              echo "✔ Patch can be applied cleanly"
-              git apply --whitespace=fix "$PATCH_FILE"
-          elif git apply --3way --check "$PATCH_FILE"; then
-              echo "⚠ Applying patch with 3-way merge"
-              git apply --3way --whitespace=fix "$PATCH_FILE"
-          else
-              echo "❌ Patch failed, generating rejects"
-              git apply --reject --whitespace=fix "$PATCH_FILE" || true
-              echo "❌ Patch could not be fully applied"
-              find . -name "*.rej"
-              echo "⚠ Continuing build despite patch failure..."
-          fi
-          echo "✔ Patch applied successfully"
-
           FILE="dlls/ntdll/unix/loader.c"
           if ! grep -q '/aarch64-windows' "$FILE"; then
             echo "Patching PE directory mapping..."
@@ -346,6 +327,26 @@ jobs:
             sed -i 's/xtajit64\.dll/libarm64ecfex.dll/g' "$TARGET_INF"
             sed -i 's/xtajit\.dll/libwow64fex.dll/g' "$TARGET_INF"
           fi
+
+          PATCH_URL="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/2.patch"
+          PATCH_FILE="syscall.patch"
+          echo "Applying external patch..."
+          wget -q -O "$PATCH_FILE" "$PATCH_URL"
+          if git apply --check "$PATCH_FILE"; then
+              echo "✔ Patch can be applied cleanly"
+              git apply --whitespace=fix "$PATCH_FILE"
+          elif git apply --3way --check "$PATCH_FILE"; then
+              echo "⚠ Applying patch with 3-way merge"
+              git apply --3way --whitespace=fix "$PATCH_FILE"
+          else
+              echo "❌ Patch failed, generating rejects"
+              git apply --reject --whitespace=fix "$PATCH_FILE" || true
+              echo "❌ Patch could not be fully applied"
+              find . -name "*.rej"
+              echo "⚠ Continuing build despite patch failure..."
+          fi
+          echo "✔ Patch applied successfully"
+
 
       # ------------------------------------------------------------
       # 8. 生成 configure 脚本
