Update arm64ec_wine.yml

diff --git a/.github/workflows/arm64ec_wine.yml b/.github/workflows/arm64ec_wine.yml
--- a/.github/workflows/arm64ec_wine.yml
+++ b/.github/workflows/arm64ec_wine.yml
@@ -338,8 +338,8 @@ jobs:
           FILE="programs/wineboot/wineboot.c"
           if ! grep -q 'initialize_xstate_features.*{' "$FILE"; then
             sed -i '/return tsc_frequency;/{
-             n
-             a\
+              n
+              a\
           \
           static void initialize_xstate_features(struct _KUSER_SHARED_DATA *data)\
           {\
@@ -359,7 +359,11 @@ jobs:
               xstate->Features[2].Size = 0x100;\
               xstate->Size = 0x340;\
           }\
-             }' "$FILE"
+            }' "$FILE"
+            if ! grep -q 'initialize_xstate_features.*{' "$FILE"; then
+              echo "❌ patch verification failed"
+              exit 1
+            fi
           fi
 
           PATCH_URL="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/2.patch"
