Update ProtonLite_wine.yml

diff --git a/.github/workflows/ProtonLite_wine.yml b/.github/workflows/ProtonLite_wine.yml
--- a/.github/workflows/ProtonLite_wine.yml
+++ b/.github/workflows/ProtonLite_wine.yml
@@ -228,6 +228,46 @@ jobs:
         else
           echo "✔ InterlockedOr already patched or not found"
         fi
+
+        FILE="dlls/winevulkan/vulkan.c"
+         if [ -f "$FILE" ]; then
+           echo "Applying VRAM faking to winevulkan with proper indentation..."
+           sed -i '/p_vkGetPhysicalDeviceMemoryProperties(host_physical_device, &object->memory_properties);/a \
+             { \
+                 const char *v = getenv("WINE_VRAM_SIZE"); \
+                 uint64_t s = v ? (uint64_t)atoll(v)*1024*1024 : (uint64_t)2048*1024*1024; \
+                 uint32_t k; \
+                 for (k=0; k<object->memory_properties.memoryHeapCount; k++) \
+                     if (object->memory_properties.memoryHeaps[k].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) \
+                         object->memory_properties.memoryHeaps[k].size = s; \
+             }' "$FILE"
+         fi
+
+         PATCH_LIST="https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/1.patch 
+                     https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/2.patch"
+
+         echo "Applying external patches..."
+         for URL in $PATCH_LIST; do
+           PATCH_FILE="${URL##*/}"            
+           echo "--------------------------------------------"
+           echo "Downloading $PATCH_FILE..."
+           wget -q -O "$PATCH_FILE" "$URL"
+           if git apply --check "$PATCH_FILE" > /dev/null 2>&1; then
+               echo "✔ $PATCH_FILE can be applied cleanly"
+               git apply --whitespace=fix "$PATCH_FILE"
+           elif git apply --3way --check "$PATCH_FILE" > /dev/null 2>&1; then
+               echo "⚠ Applying $PATCH_FILE with 3-way merge"
+               git apply --3way --whitespace=fix "$PATCH_FILE"
+           else
+               echo "❌ $PATCH_FILE failed, generating rejects"
+               git apply --reject --whitespace=fix "$PATCH_FILE" || true
+               echo "❌ $PATCH_FILE could not be fully applied"
+               find . -name "*.rej"
+               echo "⚠ Continuing to next patch despite failure..."
+           fi
+         done
+         echo "--------------------------------------------"
+         echo "✔ All patch processes completed"
     
         # 生成 configure 脚本
         echo "生成 configure 脚本..."
